network:
  rpc_url: "http://localhost:8545"
  ws_url: "ws://localhost:8546"
  chain_id: 31337  # Hardhat/Anvil local chain
  private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"  # Test key

bot:
  max_gas_price: 20000000000  # 20 gwei
  min_profit_threshold: 0.001  # 0.1% minimum profit
  strategies:
    - "arbitrage"
    - "sandwich"

performance:
  worker_threads: 4
  ring_buffer_size: 10000
  simulation_timeout_ms: 100
  max_concurrent_simulations: 50
  cpu_core_pinning: false
  core_ids: [0, 1, 2, 3]
  backpressure:
    enabled: true
    drop_policy: "oldest"  # oldest, newest, random
    high_watermark: 0.8    # Drop when buffer is 80% full
    low_watermark: 0.6     # Resume when buffer drops to 60%

monitoring:
  prometheus_port: 9090
  log_level: "debug"
