network:
  rpc_url: "https://goerli.infura.io/v3/YOUR_INFURA_KEY"
  ws_url: "wss://goerli.infura.io/ws/v3/YOUR_INFURA_KEY"
  chain_id: 5  # Goerli testnet
  private_key: ""  # Set in environment variables

bot:
  max_gas_price: 50000000000  # 50 gwei
  min_profit_threshold: 0.005  # 0.5% minimum profit
  strategies:
    - "arbitrage"

performance:
  worker_threads: 8
  ring_buffer_size: 20000
  simulation_timeout_ms: 50
  max_concurrent_simulations: 100
  cpu_core_pinning: true
  core_ids: [0, 1, 2, 3, 4, 5, 6, 7]
  backpressure:
    enabled: true
    drop_policy: "oldest"
    high_watermark: 0.85
    low_watermark: 0.65

monitoring:
  prometheus_port: 9090
  log_level: "info"
